version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: powergrid-simulator-app
    container_name: PowerGrid-simulator-app
    restart: always
    ports:
      - "5101:5000"
    volumes:
      - .:/code
    networks:
      - cab-standalone_default
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: powergrid-simulator-api
    container_name: PowerGrid-simulator-api
    restart: always
    ports:
      - "5101:5000"
    volumes:
      - .:/code
    networks:
      - cab-standalone_default

# allow for communication between simulator and cab
networks:
  cab-standalone_default:
    name: cab-standalone_default
    external: true